# Generated by Django 3.2.9 on 2021-12-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_endroit', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/androits/')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default=None, upload_to='images/logo/')),
                ('name_tag1', models.CharField(max_length=200, null=True)),
                ('name_tag2', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=400, null=True)),
                ('email', models.EmailField(default='test@travel.agency.com', max_length=254)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('agency_number', models.CharField(max_length=15, null=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('slogan', models.TextField(blank=True)),
                ('Image_principal', models.ImageField(null=True, upload_to='media/heros/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reservation_type', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('reservation_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('photo_representatif', models.ImageField(blank=True, default=None, null=True, upload_to='images/rubriques/main/')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce_name', models.CharField(max_length=200)),
                ('annonce_description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='images/annonces/pricipal/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.rubrique')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/annoces/')),
                ('annonce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.annonce')),
            ],
            options={
                'unique_together': {('annonce', 'id')},
            },
        ),
    ]
