# Generated by Django 3.2.9 on 2021-12-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='image',
            new_name='image_principale',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='main.rubrique'),
        ),
    ]
