# Generated by Django 3.2.9 on 2021-12-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211209_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_type',
        ),
    ]
