# Generated by Django 3.2.9 on 2021-12-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211211_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='video_pricipal',
            field=models.FileField(blank=True, upload_to='media/videos/'),
        ),
    ]
