# Generated by Django 3.2.9 on 2021-12-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_video_pricipal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='video_pricipal',
            new_name='video_principal',
        ),
    ]
