# Generated by Django 3.2.9 on 2021-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_video_pricipal_main_video_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='Image_principal',
            field=models.ImageField(null=True, upload_to='heros/'),
        ),
        migrations.AlterField(
            model_name='main',
            name='video_principal',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
