# Generated by Django 3.2.9 on 2021-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211218_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='post',
            field=models.TextField(default=''),
        ),
    ]
