# Generated by Django 3.2.9 on 2021-12-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_annonce_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='main.rubrique'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
